FROM node:24.18.0-alpine as development
# working directory inside the container
WORKDIR /app
# copy package.json and package-lock.json
COPY package*.json ./
# install dependencies
RUN npm install
# copy the app code
COPY . .
# start the app
CMD ["npm", "run", "start:dev"]