# =========================
# Stage 1 — Build Angular
# =========================
FROM node:24.18.0-alpine AS build

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installation reproductible
RUN npm ci

# Installer Angular CLI uniquement pour le build
RUN npm install -g @angular/cli

# Copier le code source
COPY . .

# Build production
RUN npm run build


# =========================
# Stage 2 — Nginx
# =========================
FROM nginx:stable-alpine

# Supprimer la configuration par défaut
RUN rm -rf /usr/share/nginx/html/*

# Copier l'application Angular compilée
COPY --from=build /app/dist/frontpart/browser /usr/share/nginx/html

# Configuration Nginx Angular
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
